# Generated by Django 4.2.6 on 2023-10-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o Tipo de Pet', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('rg', models.CharField(blank=True, max_length=40, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_agendada', models.DateField(verbose_name='Data Agendada')),
                ('hr_agendada', models.TimeField(verbose_name='Hora Agendada')),
                ('dt_checkin', models.DateField(verbose_name='Data Check-in')),
                ('hr_checkin', models.TimeField(verbose_name='Hora Check-in')),
                ('dt_checkout', models.DateField(verbose_name='Data Check-out')),
                ('hr_checkout', models.TimeField(verbose_name='Hora Check-out')),
                ('observacao', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'AGENDADO'), ('C', 'CANCELADO'), ('I', 'CHECK-IN'), ('O', 'CHECK-OUT'), ('R', 'RESERVADO')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('cor_predominante', models.CharField(max_length=40, verbose_name='cor predominante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.animal', verbose_name='tipo de pet')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='descrição')),
                ('numero', models.IntegerField(verbose_name='número do quarto')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite a Raça do Pet', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_agendada', models.DateField()),
                ('hr_agendada', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('BANHO', 'BANHO'), ('BANHOTOSA', 'BANHO E TOSA'), ('TOSA', 'TOSA'), ('CLINICO', 'CLINICO')], max_length=30)),
                ('obs', models.TextField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.servico')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.raca', verbose_name='raça do pet'),
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospedagemQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.hospedagem')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.pet')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstpetshop.quarto')),
            ],
        ),
    ]
