# Generated by Django 4.2.6 on 2023-10-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpetshop', '0003_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
