# Generated by Django 4.2.6 on 2023-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpetshop', '0005_remove_hospedagem_hr_agendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'AGENDADO'), ('CANCELADO', 'CANCELADO'), ('CHECK-IN', 'CHECK-IN'), ('CHECK-OUT', 'CHECK-OUT'), ('RESERVADO', 'RESERVADO')], max_length=30),
        ),
    ]
